AWSTemplateFormatVersion: 2010-09-09
Description: 'This template creates an SQS queue name data_pipeline with default encryption.
  It also creates an S3 bucket with sse-s3 and versioning enabled.'
Parameters:
  BucketName:
    Type: String
    Description: 'The name of the S3 bucket to create, must be unique.'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'data_pipeline'
      ReceiveMessageWaitTimeSeconds: 20
      KmsMasterKeyId: 'alias/aws/sqs'
Outputs:
  S3BucketName:
    Description: 'S3 bucket ID'
    Value: !Ref S3Bucket
  SQSQueueName:
    Description: 'SQS Queue ID'
    Value: !Ref SQSQueue